import {
  IconAbc, IconActivity, IconAnchor, IconAperture, IconArrowLeft, IconBarbell, IconBed, IconBolt,
  IconBoltFilled, IconBook, IconBrandDocker, IconBrandJavascript, IconBrandNodejs, IconBrandReact,
  IconBrandTypescript, IconBinaryTree2, IconBrush, IconBulb, IconCalendar, IconCamera, IconCarrot,
  IconCheck, IconChevronDown, IconChevronUp, IconCircleDot, IconClock, IconCode, IconCoffee,
  IconCrown, IconDatabase, IconDeviceDesktop, IconDiamond, IconDiamondFilled, IconDots,
  IconDownload, IconEye, IconFlame, IconFlameFilled, IconFlask, IconGitBranch, IconHeadphones,
  IconHeart, IconJumpRope, IconLayoutGrid, IconLink, IconLock, IconLungs, IconMap2,
  IconMasksTheater, IconMedal2, IconMessage, IconMicrophone,
  IconMinus, IconMaximize, IconMoon, IconMountain, IconMusic, IconNumbers, IconPackage, IconPalette,
  IconPencil, IconPlane, IconPlug, IconPlus, IconPuzzle, IconRefresh, IconRocket, IconRoute, IconRun,
  IconSalad, IconSeeding, IconServer, IconSettings, IconShare3, IconShieldLock,
  IconShoppingBag, IconSparkles, IconStar, IconStretching, IconSun, IconTarget, IconTerminal,
  IconTool, IconTrash, IconTrophy, IconUser, IconWand, IconX, IconYoga,
  IconAd2, IconBrandApple, IconBrandGoogle, IconBrandWechat, IconChevronRight, IconCircleCheck,
  IconCoin, IconGift, IconLogout, IconMail, IconPhone, IconDeviceMobile, IconCloudOff,
  IconSearch, IconShieldCheck, IconStarFilled, IconTicket, IconUpload,
  IconUsers, IconCloudDownload, IconBrandAlipay, IconBrandStripe, IconCreditCard, IconLoader2,
  IconEye as IconPreview, IconArrowBackUp, IconArrowForwardUp, IconPointer, IconAdjustments,
  type Icon as TablerIcon,
} from '@tabler/icons-react'

export const ICONS = {
  map: IconMap2, tree: IconBinaryTree2, medal: IconMedal2, settings: IconSettings,
  plus: IconPlus, minus: IconMinus, fit: IconMaximize, locate: IconTarget, edit: IconPencil,
  close: IconX, check: IconCheck, lock: IconLock, share: IconShare3, more: IconDots,
  down: IconChevronDown, up: IconChevronUp, back: IconArrowLeft, refresh: IconRefresh, trash: IconTrash,
  download: IconDownload, ai: IconSparkles, link: IconLink, wand: IconWand,
  search: IconSearch,
  energy: IconBolt, gem: IconDiamond, star: IconStar, flame: IconFlame, day: IconCalendar,
  energyFill: IconBoltFilled, gemFill: IconDiamondFilled, flameFill: IconFlameFilled,
  dot: IconCircleDot, seed: IconSeeding, book: IconBook, tool: IconTool, rocket: IconRocket,
  crown: IconCrown, trophy: IconTrophy, target: IconTarget, bulb: IconBulb, puzzle: IconPuzzle,
  eye: IconEye, heart: IconHeart, user: IconUser, clock: IconClock,
  abc: IconAbc, talk: IconMessage, num: IconNumbers, music: IconMusic, mic: IconMicrophone,
  ear: IconHeadphones, mask: IconMasksTheater, plane: IconPlane, bag: IconShoppingBag,
  code: IconCode, brush: IconBrush, git: IconGitBranch, js: IconBrandJavascript,
  ts: IconBrandTypescript, react: IconBrandReact, node: IconBrandNodejs, docker: IconBrandDocker,
  db: IconDatabase, api: IconPlug, test: IconFlask, auth: IconShieldLock, term: IconTerminal,
  pkg: IconPackage, route: IconRoute, hook: IconAnchor, server: IconServer, grid: IconLayoutGrid,
  screen: IconDeviceDesktop,
  lift: IconBarbell, run: IconRun, stretch: IconStretching, yoga: IconYoga, bed: IconBed,
  salad: IconSalad, carrot: IconCarrot, moon: IconMoon, lungs: IconLungs, rope: IconJumpRope,
  pulse: IconActivity, mountain: IconMountain, coffee: IconCoffee, sun: IconSun,
  camera: IconCamera, lens: IconAperture, palette: IconPalette,
  people: IconUsers, ad: IconAd2, pro: IconStarFilled, gift: IconGift, ticket: IconTicket,
  coin: IconCoin, upload: IconUpload, shield: IconShieldCheck, ok: IconCircleCheck,
  next: IconChevronRight, out: IconLogout, cloud: IconCloudDownload,
  alipay: IconBrandAlipay, stripe: IconBrandStripe, card: IconCreditCard, loading: IconLoader2,
  preview: IconPreview, undo: IconArrowBackUp, redo: IconArrowForwardUp,
  pointer: IconPointer, sliders: IconAdjustments,
  mail: IconMail, phone: IconPhone, device: IconDeviceMobile, nocloud: IconCloudOff,
  apple: IconBrandApple, wechat: IconBrandWechat, google: IconBrandGoogle,
} satisfies Record<string, TablerIcon>

export type IconKey = keyof typeof ICONS
